### PR TITLE
Modify sample [WIP]

### PR DESCRIPTION
**Pull request by Lavanyagaur22**

### CODE REVIEW

**Comment by harshithdwivedi** [comment]
@lavanyagaur22 make sure that this pr gets rid of *everything* that's not needed alongwith making the UI Of the same app better.

**Comment by wtrocki** [comment]
Ping me once you are happy with changes. I will do tests

**Comment by Lavanyagaur22** [comment]
@harshithdwivedi Have modified the sample. Just getting an error - While updating task, there is some issue with the context I am using there in FragmentTasks. I am using activity context in both update Task and create Task, (tried using application context, no success). Create Task function is working perfectly fine, but in the update task function, the call is not made. 
Can you please have a look at it once.

**Comment by Lavanyagaur22** [comment]
@wtrocki @harshithdwivedi The sample looks like this: (have added user and tasks)

scrren1


screen2

**Comment by harshithdwivedi** [comment]
This looks good!
Did you manage to fix the issue with the calls?

**Comment by Lavanyagaur22** [comment]
Closing in favour of #126

**Pull request closed without merging**
