### PR TITLE
Experiment with various functionality provided by apollo android client

### PR DESCRIPTION
**Pull request by Lavanyagaur22**
### Description
- Played around with graphql and apollo android client, using queries and mutations.
- Observed the responses returned by the server by logging them.
- Used the cache functionality provided by Apollo android client.

With reference to PR #8

### CODE REVIEW

**Comment by Lavanyagaur22** [comment]
@wtrocki @harshithdwivedi Please have a look at it.

**Comment by wtrocki** [comment]
I could not run thar but from just code impression we need to think how to structure app and avoid utils class. Generally split app to different areas like data, cache etc. It will help later

**Comment by Lavanyagaur22** [comment]
Utils class was just like the Application class, for implementing the singleton pattern. It contains making an Apollo client and using the inbuilt cache of it. So, should I modify the Utils class and make it Application class? The features, database, etc which I'll use by extending the Apollo functionality, I'll put those in seperate folders. WDYT?

**Comment by wtrocki** [comment]
Maybe ignore me this time. Keep structure the way it works for you and when we get some complex implementation we can think how to separate concerns.

I personally have tendency to use one of the  patterns like MVP + graphQL patterns like having model buffers and separate query layer having all together is fine. It makes no sense to bring that now

**Review by harshithdwivedi — APPROVED** [review]

**Pull request merged**
