### PR TITLE
Problem facing in adding mutation objects to the offline Queue.

### PR DESCRIPTION
**Pull request by Lavanyagaur22**
## Description 

( In reference to solving issue #29  )

I have used an ArrayList (of Type <Any>) which store mutation objects in OnFailure() method of Mutation Callback in UserData() class.

I have made n interface CustomApolloCall which extends ApolloCall and in its Enqueue and Callback method passed Void as a generic type.
Similar thing I have done with CustomMutation interface which extends Mutation.

In MainActivity, I have an offOn Button (for spike) clicking on which should fetch mutation object from the list and make a call to the server.

Screenshot 2019-06-25 at 10 50 14 AM

### Problem:

When passing mutation object from ArrayList to apollo call, I casted it to be of type CustomMutation, but ClassCast exception came: 

Screenshot 2019-06-25 at 10 51 34 AM

### CODE REVIEW

**Comment by Lavanyagaur22** [comment]
@harshithdwivedi @wtrocki Can any of you please have a look at it.

**Comment by harshithdwivedi** [comment]
Check out a new branch for each PR.
This PR contains code from already merged branches.

**Comment by Lavanyagaur22** [comment]
@harshithdwivedi I made a new branch for this PR. Don't know why it's showing like this :/

**Comment by harshithdwivedi** [comment]
You probably forgot to update your master branch.
Checkout the master branch, do a git pull and then do git checkout new
branch from your master branch.

**Pull request closed without merging**
