### PR TITLE
error : Add a POM file to the latest version of your package before p…

### PR DESCRIPTION
**Pull request by Lavanyagaur22**
Screenshot 2019-07-26 at 2 42 59 PM

As I Click on Add to JCenter, an error comes up saying
 `Please fix the following before submitting a JCenter inclusion request: Add a POM file to the latest version of your package.`

### CODE REVIEW

**Comment by Lavanyagaur22** [comment]
@harshithdwivedi Can you please help me out here.

**Comment by harshithdwivedi** [comment]
@Lavanyagaur22 Looks like the uploaded pom files are missing here
Increment the library version and then run `./gradlew cleanBuildPublish` on your terminal and see if the pom files are uploaded to jfrog?

Once that's done, you should see setup instructions on your homepage like here: 
https://bintray.com/the-dagger/event360/app.pitech.event

**Comment by Lavanyagaur22** [comment]
@harshithdwivedi Didn't work :/

**Comment by harshithdwivedi** [comment]
What's the output of that gradle task in the terminal?

**Comment by Lavanyagaur22** [comment]
It shows Build Successful, but on bintray site, it shows the same error.

**Comment by harshithdwivedi** [comment]
I meant the terminal output, can you share it here?

**Comment by Lavanyagaur22** [comment]
Screenshot 2019-07-26 at 4 22 42 PM

**Comment by Lavanyagaur22** [comment]
Screenshot 2019-07-26 at 4 41 53 PM


@harshithdwivedi This thing though I have included it in bintray{}.

**Comment by harshithdwivedi** [comment]
Can you please copy-paste the entire output instead of posting a screenshot?
Screenshots don't cover everything and as you can see a lot of build messages are hidden.

**Comment by Lavanyagaur22** [comment]
> Configure project :offix
WARNING: API 'variant.getPackageLibrary()' is obsolete and has been replaced with 'variant.getPackageLibraryProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getPackageLibrary(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
Configuration(s) specified but the install task does not exist in project :offix.

> Task :offix:cleanBuildPublish
Configuration(s) specified but the install task does not exist in project :offix.

> Task :voyager-android:offix:installApolloCodegen
npm WARN deprecated apollo-codegen@0.19.1: The 'apollo-codegen' command has been replaced with the more-powerful 'apollo' CLI. Switch to 'apollo' to ensure future updates and visit https://npm.im/apollo#code-generation for more information.

> Task :voyager-android:offix:kaptDebugKotlin
w: /Users/lavanya/GsocJboss'2019/voyager-android/offix/build/tmp/kapt3/stubs/debug/org/aerogear/offix/persistence/Database.java:8: warning: Schema export directory is not provided to the annotation processor so we cannot export the schema. You can either provide `room.schemaLocation` annotation processor argument OR set exportSchema to false.
public abstract class Database extends android.arch.persistence.room.RoomDatabase {
                ^

> Task :voyager-android:offix:compileDebugKotlin
w: /Users/lavanya/GsocJboss'2019/voyager-android/offix/src/main/java/org/aerogear/offix/Offix.kt: (171, 16): Unchecked cast: Any! to Mutation<Operation.Data, Operation.Data, Operation.Variables>
w: /Users/lavanya/GsocJboss'2019/voyager-android/offix/src/main/java/org/aerogear/offix/Offline.kt: (111, 27): The resulting type of this 'javaClass' call is Class<Offline.Companion> and not Class<Offline>. Please use the more clear '::class.java' syntax to avoid confusion
w: /Users/lavanya/GsocJboss'2019/voyager-android/offix/src/main/java/org/aerogear/offix/interceptor/LoggingInterceptor.kt: (42, 13): Variable 't1' is never used

> Task :voyager-android:offix:kaptReleaseKotlin
w: /Users/lavanya/GsocJboss'2019/voyager-android/offix/build/tmp/kapt3/stubs/release/org/aerogear/offix/persistence/Database.java:8: warning: Schema export directory is not provided to the annotation processor so we cannot export the schema. You can either provide `room.schemaLocation` annotation processor argument OR set exportSchema to false.
public abstract class Database extends android.arch.persistence.room.RoomDatabase {
                ^

> Task :voyager-android:offix:compileReleaseKotlin
w: /Users/lavanya/GsocJboss'2019/voyager-android/offix/src/main/java/org/aerogear/offix/Offix.kt: (171, 16): Unchecked cast: Any! to Mutation<Operation.Data, Operation.Data, Operation.Variables>
w: /Users/lavanya/GsocJboss'2019/voyager-android/offix/src/main/java/org/aerogear/offix/Offline.kt: (111, 27): The resulting type of this 'javaClass' call is Class<Offline.Companion> and not Class<Offline>. Please use the more clear '::class.java' syntax to avoid confusion
w: /Users/lavanya/GsocJboss'2019/voyager-android/offix/src/main/java/org/aerogear/offix/interceptor/LoggingInterceptor.kt: (42, 13): Variable 't1' is never used

> Task :voyager-android:offix:lint
Ran lint on variant release: 2 issues found
Ran lint on variant debug: 2 issues found
Wrote HTML report to file:///Users/lavanya/GsocJboss'2019/voyager-android/offix/build/reports/lint-results.html
Wrote XML report to file:///Users/lavanya/GsocJboss'2019/voyager-android/offix/build/reports/lint-results.xml

> Task :voyager-android:offix:publishProductionPublicationToMavenLocal FAILED
> Task :offix:cleanBuildPublish FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':voyager-android:offix:publishProductionPublicationToMavenLocal'.
> Failed to publish publication 'Production' to repository 'mavenLocal'
   > Invalid publication 'Production': artifact file does not exist: '/Users/lavanya/GsocJboss'2019/voyager-android/offix/build/outputs/aar/library-release.aar'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.1.1/userguide/command_line_interface.html#sec:command_line_warnings

**Comment by harshithdwivedi** [comment]
Check the contents of the following file, and see if that exists or not.

```
Users/lavanya/GsocJboss'2019/voyager-android/offix/
build/outputs/aar/library-release.aar

```

If it doesn't exist, then check to see what's the folder that is not
present.
I'm sure that this has to do something with the package name and folder
path issues.

**Comment by Lavanyagaur22** [comment]
Done 👍

**Comment by harshithdwivedi** [comment]
Awesome!
Can you share the link of the hosted library?

Also, we will probably need to add `@Keep` annotation to our model classes to prevent proguard from obfuscating them

**Comment by Lavanyagaur22** [comment]
CircleCI failing because it's unable to find the local properties file as we have added it in gitignore. Trying to fix it. Can probably run a function in circleci yaml file that runs before building up gradle and generates a local file for it.

**Comment by harshithdwivedi** [comment]
Yep, that's a good idea.
It should be doable.

**Comment by Lavanyagaur22** [comment]
@harshithdwivedi Can you please have a look at it.

https://bintray.com/lavanyagaur22/Offix/Offix -> link to library.

Dependency: `compile 'org.aerogear.offix:library:1.0.2'`

**Comment by harshithdwivedi** [comment]
Good job!
* `implementation` :p

**Review by harshithdwivedi — APPROVED** [review]

**Pull request merged**
