### PR TITLE
Simplifying sample app 

### PR DESCRIPTION
**Pull request by Lavanyagaur22**
### Description
Simplified sample app, removed MVVM pattern. Adding new graphql files according to the new schema.

### CODE REVIEW

**Comment by Lavanyagaur22** [comment]
@harshithdwivedi @wtrocki Added new graphql files of mutations and queries according to our new schema. Also modified the sample app. 
ps: Still WIP till we fix that server error of returning an error in response.

**Comment by harshithdwivedi** [comment]
@Lavanyagaur22 Also add some screenshots of the app maybe?

**Comment by wtrocki** [comment]
@Lavanyagaur22  I have noticed that we have made change in server. This `*` is not going to work according to Knex documentation - does that work for you?

If you revert back to the original code and add console log - do you see proper data?

**Comment by Lavanyagaur22** [comment]
> @Lavanyagaur22 Also add some screenshots of the app maybe?

App working fine for Online part, now have to check for offline. So should I add the screenshots of the app when doing mutations online?

**Comment by Lavanyagaur22** [comment]
> @Lavanyagaur22 Also add some screenshots of the app maybe?

@harshithdwivedi App working fine for Online part, now have to check for offline. So should I add the screenshots of the app when doing mutations online?

**Review by harshithdwivedi — APPROVED** [review]

**Pull request merged**
