### PR TITLE
Added subscriptions support

### PR DESCRIPTION
**Pull request by Lavanyagaur22**
Enabled subscriptions in server.

### CODE REVIEW

**Comment by Lavanyagaur22** [comment]
@harshithdwivedi Please merge this.

**Review by harshithdwivedi — APPROVED** [review]

**Comment by wtrocki** [comment]
@Lavanyagaur22 I think we forgot to do `graphback generate` as this will trigger changes in resolvers.

**Comment by Lavanyagaur22** [comment]
> @Lavanyagaur22 I think we forgot to do `graphback generate` as this will trigger changes in resolvers.

Yeah, forgot by mistake. Fixed this in #125 .
@wtrocki @harshithdwivedi After generating files for the same, it automatically changed the id and fields to `*` which initially gave problems as you said. So do we have to revert them back again?

**Comment by wtrocki** [comment]
Do npm install graphback-cli -g 
Your version might be outdated

**Pull request merged**
