### PR TITLE
App not building. 

### PR DESCRIPTION
**Pull request by Lavanyagaur22**
@harshithdwivedi Please check it out, having some problems building the app.

### CODE REVIEW

**Comment by danielpassos** [comment]
```
> Task :sample:generateDebugApolloIR FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Some problems were found with the configuration of task ':sample:generateDebugApolloIR'.
> Value 'main GraphQL source' specified for property '$1' cannot be converted to a file.
> Value 'debug GraphQL source' specified for property '$2' cannot be converted to a file.
```

**Comment by wtrocki** [comment]
@Lavanyagaur22 Unrelated but worth mentioning - we are working with a not rebased master. Please bring master changes to your branch by rebasing it.

**Comment by Lavanyagaur22** [comment]
@danielpassos Yeah, exactly the same error was coming when the latest gradle version was used.
I reverted back to gradle 4.6 and it worked perfectly fine. I think some issues there with gradle 5 (as mentioned in an issue in apollo repo too)

**Comment by Lavanyagaur22** [comment]
@wtrocki Yeah, this branch was just for solving that error, no use as of now. I'll rebase it when pushing the code.

**Pull request closed without merging**
