### PR TITLE
Implementing cache and subscriptions

### PR DESCRIPTION
**Pull request by Lavanyagaur22**
### Description
1. Added ApolloQueryWatcher and RefetchQueries on mutation.
2. Added subscriptions for mutations ( Working for update mutation as of now, as was checking for them)

## Problem 
1. While running the server with the new database, cache first still showing the outdated data (ie data of the DB which was killed)

### CODE REVIEW

**Comment by wtrocki** [comment]
> While running the server with the new database, cache first still showing the outdated data (ie data of the DB which was killed)

Expected behavior of cache? In classicall cache invalidation scenario server need to intentionally send information to invalidate cache, but since we reset data this is not going to happen. There is no cache invalidation supported currently but we can wipe out entire cache. 

Like if network returns no results does it eventualy gets updated to []?
Cache is not going to be cleared but at least we should see query being updated to [] after network request.

**Comment by wtrocki** [comment]
Any reason why this is not merged? Was this spike only?

**Comment by Lavanyagaur22** [comment]
Actually, I made this for asking the solution to the problem faced related to cache. Now everything is in one PR (this commit has the all the work done till now https://github.com/aerogear/offix-android/commit/51c7a5710010c6088e5f3e939d2ab7c4b53e959b ). 

The offline store is our main aim, but yes spikes done with apollo cache and stuff should have been merged. Also, the app was also restructured according to MVVM pattern.

**Comment by wtrocki** [comment]
Perfect. Sorry I have forgot about it

**Pull request closed without merging**
