### PR TITLE
Added Instrumentation and Unit test

### LINKED ISSUE #144: Write unit tests for the sample app.
We almost forgot this! 😄

### PR DESCRIPTION
**Pull request by xatuke**
### Description
Include a summary of the change and relevant motivation/context. List any dependencies that are required for this change.

Fixes #144 

### Type of Change:
**Delete irrelevant options.**

- Code
- Quality Assurance

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality)

### How Has This Been Tested?
They Don't break the app, yet :)

##### Checklist

- [x] tests are included

### CODE REVIEW

**Comment by harshithdwivedi** [comment]
@crowded-geek #159 might be a good issue for you to explore as well. Maybe @Lavanyagaur22 can create multiple tasks for that issue :)

**Comment by Lavanyagaur22** [comment]
Also @crowded-geek I've made 2 separate tasks for writing unit tests for the offix library and sample app.
So while writing unit tests for sample, you will learn and get an idea of how to write tests and then try to implement that knowledge in library as well.

**Comment by xatuke** [comment]
@Lavanyagaur22 So for the task i've currently put on review, do i have to add something to this?

**Comment by xatuke** [comment]
@harshithdwivedi Will look into it! :smile:

**Comment by Lavanyagaur22** [comment]
@crowded-geek Good work! Also, can you please add some more tests to check whether the task has been created/updated successfully or not.

**Comment by xatuke** [comment]
@Lavanyagaur22 Yes mam, sure. I've posted some doubts I have on gitter :)

**Comment by Lavanyagaur22** [comment]
@crowded-geek  please have a look at the tests that are written in the [apollo library](https://github.com/apollographql/apollo-android)
Tests: https://github.com/apollographql/apollo-android/tree/master/apollo-runtime/src/test/java/com/apollographql/apollo

For writing unit tests for sample by mocking apollo client and all the parameters that it requires, the above link would surely help you.

**Comment by Lavanyagaur22** [comment]
Also, @crowded-geek Just add the unit tests in this branch, let's make another task for adding the instrument tests in it. Like you can check here that whether the parameters passed in the mutation are correct or not. And for instrument tests, kindly make another PR.

So for checking whether the mutation has been created/updated successfully or not, make another pr (the task for that would soon be visible on GCI dashboard)

**Comment by xatuke** [comment]
@Lavanyagaur22 I've added the validation test, kindly check :)

**Comment by Lavanyagaur22** [comment]
@crowded-geek Code looks good 👍 
Can you please squash your commits and also add a working gif of the sample?? 
You can take help from here: https://stackoverflow.com/a/5201642/10189663

**Comment by xatuke** [comment]
The commits wasn't squashing so I'll create a new PR :) and close this one;

**Pull request closed without merging**
