### PR TITLE
Implementation Of offline Store.

### PR DESCRIPTION
**Pull request by Lavanyagaur22**
### Description
(With reference to issue #25)

### Classes and Functionalities Added:

- #### GenericMutation class
This class helps to create an object of mutation stored in our offline store( local database) and this is passed to the Apollo client while making a call to the server when online.

This class implements the Mutation interface, and the approach here is to recreate the generated classes in such a way that it's generic in nature.This new class will have setters which set the query document, variables, operation-Id, etc. So when we are ready to send the offline mutation to the server, we will simply create an object of this new class and set the values via the setters which we can get from the database. In this way we can have a proper object that can be passed to mutate() function of the apollo client.

- #### OfflineMutationsWorker class
Workmanager that replicates the mutations to the server that are stored in the database. Post firing the mutation, it is deleted from the DB.

- Added ApolloQueryWatcher and RefetchQueries on processing mutations.
- Added subscriptions for mutations ( Working for update mutation as of now, as was checking for them)

### Problem:
Having some trouble while making an array of ResponseField (in Generic Mutation Class) which says:

java.lang.ClassCastException: java.lang.Object[] cannot be cast to com.apollographql.apollo.api.ResponseField[]

Screenshot 2019-06-23 at 5 29 46 PM

### CODE REVIEW

**Comment by Lavanyagaur22** [comment]
@harshithdwivedi Please have a look at this.

**Comment by harshithdwivedi** [comment]
This is the error that I get while trying to run `./gradlew assemble`

```
 e: C:\Users\harsh\Desktop\StudioProjects\voyager-android\sample\build\tmp\kapt3\stubs\debug\org\aerogear\graphqlandroid\persistence\Mutation.java:15: error: Cannot figure out how
to save this field into database. You can consider adding a type converter for it.
    private final com.apollographql.apollo.api.OperationName operationName = null;
                                                             ^
e: C:\Users\harsh\Desktop\StudioProjects\voyager-android\sample\build\tmp\kapt3\stubs\debug\org\aerogear\graphqlandroid\persistence\Mutation.java:17: error: Cannot figure out how
to save this field into database. You can consider adding a type converter for it.
    private final org.json.JSONObject valuemap = null;
                                      ^
e: C:\Users\harsh\Desktop\StudioProjects\voyager-android\sample\build\tmp\kapt3\stubs\debug\org\aerogear\graphqlandroid\persistence\MutationDao.java:23: error: Deletion methods mu
st either return void or return int (the number of deleted rows).
    public abstract org.aerogear.graphqlandroid.persistence.Mutation deleteCurrentMutation(int sno);
```

Try googling to see what the solution is, apparently you can't store `OperationName` and `JSONObject`
into the database directly with room; you'll need to write a TypeConverter for it.

**Comment by harshithdwivedi** [comment]
Try to avoid emojis in commit messages :p

**Comment by wtrocki** [comment]
We use conventional commits in project

**Comment by harshithdwivedi** [comment]
+1
Here's a good guide on how to name your commit messages; https://udacity.github.io/git-styleguide/

@wtrocki feel free to correct the link if aerogear follows a different message style :)

**Comment by harshithdwivedi** [comment]
@Lavanyagaur22 is this work in progress?

**Comment by Lavanyagaur22** [comment]
@harshithdwivedi Please can you have a look at it.  (https://github.com/aerogear/offix-android/pull/27/commits/51c7a5710010c6088e5f3e939d2ab7c4b53e959b)

**Comment by harshithdwivedi** [comment]
@lavanyagaur22 I'd suggest debugging the arraylist in line 166 more closely to see if it actually contains objects of the type ResponseField or Object.

Try printing and logging the datatype of all the elements in the arraylist explicitly,  maybe some of them are of Object type.

**Comment by Lavanyagaur22** [comment]
@wtrocki @harshithdwivedi Have updated PR description too.

**Comment by harshithdwivedi** [comment]
Nice, that's more like it! 😎

**Comment by wtrocki** [comment]
Perfect. Can you explain the thought process that pushed us to create generic mutation class? What will be the flow here? It is not trivia to get that info from PR. My understanding:

if offline we transform existing mutation into generic one and persist it? When online again we read it and execute mutation again?

Do we still execute in the same observable flow so users will still recievie data? If yes how we going to prevent from class cast exceptions? (See your problem above)

This looks really clever but I think that we overengineered this - however there is not much info in PR or issue for me to be sure. 

For example we can simply hold original mutation input object in memory and just reuse it when we become online again. This object will look different depending if we use InputTypes or direct arguments so having generic one is very hard task due to strong typing in Kotlin/java. Additionally things will start crashing when we add other elements to schema like scalars or directives. We can persist any object to database.  Restoration will be another problem we can think of in separate issue/PR and it will be corner case - when app is restarted. We already done some nice investigations for restoration so I would love to see new issue explaining your though process.

For future lets make sure we document approach we want to take and let community to comment on it. Some of the problems can be very hard to solve because of the wrong approach we are taking. We can save time and do much better if we try to explain it first.

I really want to help here and this will be possible if we start communicating our intentions before we code. This PR is great and by no means I want to say that we should scrap it - we simply need more info and see how we can resolve root of the problem instead of single instance ( check XY problem in google)

**Comment by Lavanyagaur22** [comment]
> if offline we transform existing mutation into generic one and persist it? When online again we read it and execute mutation again?

Yes, this approach tries to achieve this (also updated description). However in the process of achieving this, till now I am unable to solve class cast exceptions occurring while building up this generic class.


> For example we can simply hold original mutation input object in memory and just reuse it when we become online again. This object will look different depending if we use InputTypes or direct arguments so having generic one is very hard task due to strong typing in Kotlin/java.

I agree with you. 
Also would be nice, if you can explain a bit more of what do you here mean by simply holding original mutation input object in memory and just reusing it when we become online again.
Like, `mutation=UpdateCurrentTaskMutation.builder().id(id).title(title).version(version).build()` , this is the original mutation object, you meant storing this as it is? If yes, then we would have to change our approach of saving data in DB and yes as you mentioned we can have a discussion on approaches of Restoration in another PR.

**Comment by Lavanyagaur22** [comment]
> This object will look different depending if we use InputTypes or direct arguments so having generic one is very hard task due to strong typing in Kotlin/java.

I totally agree with it. In the process of implementing it, mapping response data returned from server seems to be a bit difficult.

**Comment by wtrocki** [comment]
In js we have access to original object passed to mutation in interceptor. We can simply hold of array of mutations objects no matter what type and retrigger them when online. Storage and restore after restart is separate concern. Original spike was to figure out mutation object fields and store it. We need separate ticket now to build queue mechanism for offline changes. Without queue (linked list) we cannot perform many operations that will be required.

**Comment by wtrocki** [comment]
Going to create task tommorow and we can chat about it

**Comment by harshithdwivedi** [comment]
@wtrocki won't we loose access to the object once the app is closed?
Isn't saving it in the db a better idea?

**Comment by wtrocki** [comment]
This will be not about InMemory vs Storage. We need to do both.

**Pull request closed without merging**
